### ISSUE TITLE
I like port your code to Rust language :D

### ISSUE THREAD

**Issue by ghost** [Gjum/pyAgar.io#11]
Because gagar sometimes will "crash" and "lag" well...

**Comment by metalmatze** [comment]
What about go?

**Comment by ghost** [comment]
ok :D

**Comment by Gjum** [comment]
Oh, cool! I'm curious what you'll create.

If you have any questions, you might want to join us in the [`#agariomods` IRC channel on the Rizon network](http://irc.lc/rizon/agariomods/CodeBlob@@@), there are many people who can help you.
